name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t oliyan/4inventory-backend:latest ./backend
          docker push oliyan/4inventory-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t oliyan/4inventory-backend:latest ./frontend
          docker push oliyan/4inventory-backend:latest
